# Generated by Django 2.1.7 on 2019-03-30 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190329_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffregistration',
            name='otp',
            field=models.TextField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='file_upload',
            field=models.ImageField(blank=True, null=True, upload_to='passport/'),
        ),
    ]
