# Generated by Django 2.1.7 on 2019-04-01 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190330_1428'),
    ]

    operations = [
        migrations.CreateModel(
            name='passwordset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staffid', models.CharField(blank=True, max_length=6, null=True)),
                ('security_question', models.CharField(blank=True, max_length=100, null=True)),
                ('answer', models.CharField(blank=True, max_length=100, null=True)),
                ('url', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='clientlogin',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='stafflogin',
            name='last_login',
        ),
        migrations.AddField(
            model_name='clientlogin',
            name='passportnumber',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='clientlogin',
            name='status',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='stafflogin',
            name='designation',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='stafflogin',
            name='status',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
