# Generated by Django 2.1.7 on 2019-04-02 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190401_1430'),
    ]

    operations = [
        migrations.CreateModel(
            name='tripplan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tripid', models.CharField(blank=True, max_length=6, null=True)),
                ('batch', models.CharField(blank=True, max_length=6, null=True)),
                ('designation', models.CharField(blank=True, max_length=70, null=True)),
                ('year', models.CharField(blank=True, max_length=6, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='stafflogin',
            name='user_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
